site_name: cat-procs-ayto-tfe
site_name: Catálogo de procedimientos municipales comunes de la Isla de Tenerife
site_description: Documentación de los Procedimientos administrativos de los municipios de la Isla de Tenerife
site_url: https://clebap.github.io/cat-proc/

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
  custom_dir: overrides

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.details

extra_css:
  - assets/css/estilos.css
extra_javascript:
  - assets/js/filtros.js
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js

nav:
  - Inicio: 
    - Introducción: index.md
    - Familias: familias.md
    - Mantenimiento: mantenimiento.md
  - Buscador: buscador.md
  - Fichas:
    - ACTIVIDAD ECONÓMICA Y CONSUMO:
        - Baja voluntaria de la autorización para el ejercicio de la venta ambulante: fichas/C057.md
        - Licencia de actividad (modificación o renuncia): fichas/C066.md
        - Licencia de actividades y espectáculos públicos: fichas/C067.md
        - Solicitud de adhesión al sistema de arbitraje: fichas/C076.md
        - Solicitud de mediación: fichas/C046.md
    - AGUA Y  RESIDUOS:
        - Abastecimiento de aguas (baja): fichas/C022.md
        - Abastecimiento de aguas (cambio de titularidad): fichas/C017.md
        - Solicitud de licencia de conexión a las redes de aguas: fichas/C015.md
        - Verificación, lectura o cambio de ubicación de contadores de aguas: fichas/C055.md
    - ALTA TERCEROS:
        - Alta a terceros: fichas/C007.md
    - ANIMALES:
        - Alta, baja o modificación de datos en el registro de animales: fichas/C023.md
        - Solicitud de licencia para la tenencia de animales potencialmente peligrosos: fichas/C010.md
    - ARCHIVO:
        - Solicitud de consulta de fondos del archivo: fichas/C083.md
    - CEMENTERIOS:
        - Autorización de usos funerarios: fichas/C025.md
        - Cambio de titularidad de derecho funerario: fichas/C004.md
        - Exhumación de cadáveres y restos humanos: fichas/C005.md
    - FERIAS, ABASTOS, MERCADOS, ETC.:
        - Autorización para el ejercicio de venta ambulante: fichas/C056.md
    - GESTIÓN FISCAL Y TRIBUTARIA:
        - Autoliquidación: fichas/C024.md
        - Comunicación del cambio de datos que figuran en el padrón fiscal: fichas/C058.md
        - Domiciliación bancaria de recibos periódicos: fichas/C019.md
        - Interposición de un recurso de reposición de actos de naturaleza tributaria: fichas/C065.md
        - Liquidación (a instancia de parte): fichas/C068.md
        - Solicitud de aplazamiento o fraccionamiento de obligaciones tributarias: fichas/C038.md
        - Solicitud de bonificación o exención de un tributo: fichas/C079.md
        - Solicitud de certificado de deuda a mi favor: fichas/C080.md
        - Solicitud de declaración de nulidad de pleno derecho de actos administrativos de naturaleza tributaria: fichas/C084.md
        - Solicitud de devolución de ingresos indebidos: fichas/C044.md
        - Solicitud de la devolución de ingresos derivada de la normativa del tributo (art. 31 lgt): fichas/C085.md
    - INFRAESTRUCTURA VIARIA:
        - Aviso de incidencia en la vía pública: fichas/C012.md
        - Corte de la vía pública: fichas/C029.md
        - Solicitud para la gestión de la tarjeta de aparcamiento para personas en situación de discapacidad: fichas/C089.md
        - Solicitud para la renumeración o denominación de una vía pública: fichas/C090.md
    - INSTANCIA GENERAL:
        - Instancia general: fichas/C002.md
    - PARTICIPACIÓN CIUDADANA:
        - Ejercicio de derechos ante el registro de asociaciones: fichas/C060.md
        - Participación en la elaboración de normativa: fichas/C069.md
        - Petición de consulta popular: fichas/C037.md
    - PATRIMONIO:
        - Solicitud de uso puntual de un bien: fichas/C051.md
    - POBLACIÓN Y TERRITORIO:
        - Certificado / volante de empadronamiento: fichas/C026.md
        - Solicitud de alta o renovación de la inscripción en el padrón municipal de habitantes: fichas/C003.md
        - Solicitud de baja en el padrón municipal de habitantes: fichas/C006.md
        - Solicitud de modificación de datos en el padrón municipal de habitantes: fichas/C047.md
        - Solicitud para la celebración de matrimonio civil: fichas/C052.md
    - POLICÍA LOCAL Y PROTECCIÓN CIVIL:
        - Consignación en la oficina de objetos perdidos: fichas/C028.md
        - Solicitud de tarjeta de armas: fichas/C021.md
    - PROBLACIÓN Y TERRITORIO:
        - Solicitud de certificado o volante de convivencia: fichas/C082.md
    - PROMOCIÓN DE LA CULTURA:
        - Inscripción en actividades y cursos: fichas/C063.md
    - PROTECCIÓN DE DATOS:
        - Ejercicio de los derechos de rectificación, supresión, limitación, portabilidad u oposición en relación con datos de carácter personal: fichas/C031.md
        - Ejercicio del derecho de acceso (datos de carácter personal): fichas/C008.md
        - Formulario de contacto con el delegado de protección de datos: fichas/C061.md
    - QUEJAS Y SUGERENCIAS:
        - Quejas y sugerencias: fichas/C009.md
        - Reclamaciones de consumo: fichas/C072.md
        - Reclamación contra la solicitud de información accesible y queja: fichas/C071.md
        - Solicitudes de información accesible y quejas: fichas/C091.md
    - RECURSOS HUMANOS:
        - Solicitud de cambio de puesto de trabajo: fichas/C041.md
    - RESPONSABILIDAD PATRIMONIAL:
        - Solicitud de responsabilidad patrimonial: fichas/C016.md
    - SECRETARÍA GENERAL:
        - Comunicaciones sobre requisitos de accesibilidad: fichas/C059.md
        - Comunicación: fichas/C027.md
        - Declaración responsable: fichas/C030.md
        - Interposición de recurso administrativo: fichas/C064.md
        - Servicios públicos (alta, baja o modificación): fichas/C073.md
        - Solicitud de acceso a una notificación rechazada: fichas/C074.md
        - Solicitud de autorización: fichas/C040.md
        - Solicitud de certificado o informe: fichas/C042.md
    - SERVICIOS BÁSICOS:
        - Licencia de auto -taxi (transmisión): fichas/C033.md
        - Licencia de vehículos especiales: fichas/C034.md
        - Solicitud de la tarjeta de aparcamiento para residentes en zonas de estacionamiento limitado: fichas/C086.md
        - Sustitución de un vehículo sujeto a una licencia de auto-taxi: fichas/C054.md
    - SERVICIOS SOCIALES:
        - Acceso al servicio de teleasistencia o de ayuda a domicilio: fichas/C018.md
        - Ingreso en centro de asistencia social: fichas/C062.md
        - Solicitud de alta en los servicios sociales: fichas/C077.md
        - Solicitud de prestación de servicios sociales: fichas/C049.md
    - SUBVENCIONES:
        - Justificación de subvención concedida: fichas/C014.md
        - Solicitud de certificado de una subvención concedida: fichas/C020.md
        - Subvenciones directas o nominativas: fichas/C053.md
    - TESORERÍA:
        - Constitución de garantía: fichas/C013.md
        - Solicitud de devolución de garantía: fichas/C043.md
    - TRANSPARENCIA:
        - Derecho de acceso a la información pública: fichas/C001.md
        - Solicitud de reuniones y entrevistas con el personal de esta entidad: fichas/C088.md
    - URBANISMO:
        - Licencia de aprovechamiento: fichas/C032.md
        - Modificación del planeamiento de desarrollo: fichas/C035.md
        - Modificación, revocación o renuncia de la licencia de ocupación: fichas/C036.md
        - Planeamiento general (modificación): fichas/C070.md
        - Solicitud de actuación urbanística: fichas/C075.md
        - Solicitud de aprobación de planeamiento de desarrollo: fichas/C039.md
        - Solicitud de aprobación de un proyecto de compensación: fichas/C078.md
        - Solicitud de certificado o informe urbanístico: fichas/C081.md
        - Solicitud de licencia de ocupación: fichas/C045.md
        - Solicitud de licencia o autorización urbanística: fichas/C087.md
        - Solicitud de modificación o renuncia de una licencia urbanística: fichas/C048.md
        - Solicitud de recepción de obras de urbanización: fichas/C050.md